# Generated by Django 4.0.1 on 2022-01-30 09:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('buyerId', models.AutoField(primary_key=True, serialize=False)),
                ('mobile_no', models.CharField(blank=True, max_length=50, null=True)),
                ('designation', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('address_line_1', models.CharField(blank=True, max_length=550, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=550, null=True)),
                ('landmark', models.CharField(blank=True, max_length=550, null=True)),
                ('pincode', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='Active', max_length=200)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('companyId', models.AutoField(primary_key=True, serialize=False)),
                ('industry', models.CharField(blank=True, default='NA', max_length=50, null=True)),
                ('overview', models.TextField(blank=True, max_length=500, null=True)),
                ('tageline', models.CharField(blank=True, default='NA', max_length=500, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images')),
                ('company_name', models.CharField(blank=True, default='NA', max_length=50, null=True)),
                ('report_pdf', models.FileField(blank=True, upload_to='company_pdf')),
                ('price', models.IntegerField(blank=True, null=True)),
                ('lot_size', models.IntegerField(blank=True, null=True)),
                ('total_available_share', models.IntegerField(blank=True, null=True)),
                ('face_value', models.IntegerField(blank=True, null=True)),
                ('cin', models.CharField(blank=True, default='NA', max_length=50, null=True)),
                ('tan', models.CharField(blank=True, default='NA', max_length=50, null=True)),
                ('pan', models.CharField(blank=True, default='NA', max_length=50, null=True)),
                ('status', models.CharField(default='Active', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyMaster',
            fields=[
                ('companyMasterId', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=50, null=True)),
                ('tageline', models.CharField(blank=True, default='NA', max_length=50, null=True)),
                ('logo', models.ImageField(blank=True, upload_to='media/master')),
                ('address_line_1', models.CharField(blank=True, max_length=550, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=550, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('pincode', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_1', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_2', models.CharField(blank=True, max_length=50, null=True)),
                ('facebook_account_link', models.CharField(blank=True, max_length=550, null=True)),
                ('twitter_account_link', models.CharField(blank=True, max_length=550, null=True)),
                ('linked_link', models.CharField(blank=True, max_length=550, null=True)),
                ('instagram_link', models.CharField(blank=True, max_length=550, null=True)),
                ('about_us', models.CharField(blank=True, default='NA', max_length=500, null=True)),
                ('mission', models.CharField(blank=True, default='NA', max_length=500, null=True)),
                ('vission', models.CharField(blank=True, default='NA', max_length=500, null=True)),
                ('website', models.CharField(blank=True, default='NA', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('contactUsId', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, default='NA', max_length=50, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('location', models.CharField(blank=True, default='NA', max_length=50, null=True)),
                ('identuty', models.CharField(blank=True, default='NA', max_length=50, null=True)),
                ('want_to', models.CharField(blank=True, default='NA', max_length=500, null=True)),
                ('message', models.CharField(blank=True, default='NA', max_length=500, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(blank=True, default='NA', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('reviewsId', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(blank=True, max_length=500, null=True)),
                ('holder_name', models.CharField(blank=True, default='NA', max_length=50, null=True)),
                ('date', models.CharField(default=datetime.datetime(2022, 1, 30, 14, 38, 7, 341160), max_length=23)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('sellerId', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='NA', max_length=50)),
                ('last_name', models.CharField(default='NA', max_length=50)),
                ('mobile_no', models.CharField(default='NA', max_length=50)),
                ('email', models.CharField(default='NA', max_length=50)),
                ('country', models.CharField(default='NA', max_length=50)),
                ('state', models.CharField(default='NA', max_length=50)),
                ('city', models.CharField(default='NA', max_length=50)),
                ('address_line_1', models.CharField(default='NA', max_length=550)),
                ('address_line_2', models.CharField(default='NA', max_length=550)),
                ('landmark', models.CharField(default='NA', max_length=550)),
                ('pincode', models.CharField(default='NA', max_length=50)),
                ('identity', models.CharField(default='NA', max_length=550)),
                ('company_name', models.CharField(default='NA', max_length=50)),
                ('status', models.CharField(default='Active', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('serviceId', models.AutoField(primary_key=True, serialize=False)),
                ('service', models.TextField(blank=True, max_length=1500, null=True)),
                ('companyId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_pannel.company')),
            ],
        ),
        migrations.CreateModel(
            name='Rationle',
            fields=[
                ('rationleId', models.AutoField(primary_key=True, serialize=False)),
                ('rationle', models.TextField(blank=True, max_length=1500, null=True)),
                ('companyId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_pannel.company')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('productsId', models.AutoField(primary_key=True, serialize=False)),
                ('products', models.TextField(blank=True, max_length=1500, null=True)),
                ('companyId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_pannel.company')),
            ],
        ),
        migrations.CreateModel(
            name='PastPerformance',
            fields=[
                ('pastPerformanceId', models.AutoField(primary_key=True, serialize=False)),
                ('pre_IPO_selling_price', models.IntegerField(blank=True, null=True)),
                ('ipo_band_price', models.IntegerField(blank=True, null=True)),
                ('listing_price', models.IntegerField(blank=True, null=True)),
                ('companyId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_pannel.company')),
            ],
        ),
        migrations.CreateModel(
            name='IndustryOverview',
            fields=[
                ('industryOverviewId', models.AutoField(primary_key=True, serialize=False)),
                ('industry_overview', models.TextField(blank=True, max_length=1500, null=True)),
                ('companyId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_pannel.company')),
            ],
        ),
        migrations.CreateModel(
            name='Evalution',
            fields=[
                ('evalutionId', models.AutoField(primary_key=True, serialize=False)),
                ('evalution', models.TextField(blank=True, max_length=1500, null=True)),
                ('companyId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_pannel.company')),
            ],
        ),
        migrations.CreateModel(
            name='DealsRequest',
            fields=[
                ('dealsRequestId', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(blank=True, max_length=10, null=True)),
                ('share_qauntity', models.IntegerField(blank=True, null=True)),
                ('share_price', models.IntegerField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=500, null=True)),
                ('subject', models.CharField(blank=True, max_length=500, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('buyerId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_pannel.buyer')),
                ('companyId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_pannel.company')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='sellerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_pannel.seller'),
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='NA', max_length=550, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('category', models.FileField(blank=True, upload_to='media/bolg/category')),
                ('viewCount', models.IntegerField(blank=True, default=350, null=True)),
                ('image', models.ImageField(blank=True, upload_to='media/bolg')),
                ('par1', models.TextField(blank=True, default='NA', max_length=500, null=True)),
                ('par2', models.TextField(blank=True, default='NA', max_length=500, null=True)),
                ('par3', models.TextField(blank=True, default='NA', max_length=500, null=True)),
                ('par4', models.TextField(blank=True, default='NA', max_length=500, null=True)),
                ('status', models.CharField(default='Active', max_length=200)),
                ('auth', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('awardId', models.AutoField(primary_key=True, serialize=False)),
                ('award', models.TextField(blank=True, max_length=500, null=True)),
                ('companyId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_pannel.company')),
            ],
        ),
        migrations.CreateModel(
            name='AnnualReport',
            fields=[
                ('annualReportId', models.AutoField(primary_key=True, serialize=False)),
                ('annual_report', models.FileField(blank=True, upload_to='annual_pdf')),
                ('companyId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_pannel.company')),
            ],
        ),
        migrations.CreateModel(
            name='AboutCompany',
            fields=[
                ('AboutCompanyId', models.AutoField(primary_key=True, serialize=False)),
                ('about_Company', models.TextField(blank=True, max_length=1500, null=True)),
                ('companyId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_pannel.company')),
            ],
        ),
    ]
