# Generated by Django 4.0.1 on 2022-01-31 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pannel', '0002_alter_reviews_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='date',
            field=models.CharField(default=datetime.datetime(2022, 1, 31, 17, 32, 7, 751295), max_length=23),
        ),
    ]
